# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('/Users/wasdwasd0105/GitHub/7zip-pyside/bin/macos/7zz-mango', 'bin/macos'),('/Users/wasdwasd0105/GitHub/7zip-pyside/pics/7-zip-logo.png', 'pics')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=True,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [('v', None, 'OPTION')],
    exclude_binaries=True,
    name='7zip-gui',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch="universal2",
    codesign_identity=None,
    entitlements_file='/Users/wasdwasd0105/GitHub/7zip-pyside/private/main_app.entitlements',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='7zip-gui',
)
app = BUNDLE(
    coll,
    name='7-Zip Archiver.app',
    icon='./7z.icns',
    bundle_identifier='com.mangofestival.7zip-gui',
    info_plist={'NSPrincipalClass': 'NSApplication',
        'NSAppleScriptEnabled': False,
        'LSBackgroundOnly': False,
        'NSRequiresAquaSystemAppearance': 'No',
        'CFBundlePackageType': 'APPL',
        'CFBundleSupportedPlatforms': ['MacOSX'],
        'CFBundleIdentifier': 'com.mangofestival.7zip-gui',
        'CFBundleShortVersionString': '1.0.1',
        'CFBundleVersion': '3.0.1',
        'LSMinimumSystemVersion': '10.15',
        'LSApplicationCategoryType': 'public.app-category.utilities',
        'ITSAppUsesNonExemptEncryption': False,
        'CFBundleDocumentTypes': [{'CFBundleTypeExtensions': ['zip'],
          'CFBundleTypeRole': 'Editor',
          'LSHandlerRank': 'Default',
          'CFBundleTypeName': 'ZIP Archive',
          'LSItemContentTypes': ['com.pkware.zip-archive'],
          'NSDocumentClass': 'YourAppDocumentClass'},
         {'CFBundleTypeExtensions': ['zip',
           'z01',
           'z02',
           'z03',
           'z04',
           'z05',
           'z06',
           'z07',
           'z08',
           'z09',
           'z10',
           'z11',
           'z12',
           'z13',
           'z14',
           'z15',
           'z16',
           'z17',
           'z18',
           'z19',
           'z20',
           'z21',
           'z22',
           'z23',
           'z24',
           'z25',
           'z26',
           'z27',
           'z28',
           'z29',
           'z30',
           'z31',
           'z32',
           'z33',
           'z34',
           'z35',
           'z36',
           'z37',
           'z38',
           'z39',
           'z40',
           'z41',
           'z42',
           'z43',
           'z44',
           'z45',
           'z46',
           'z47',
           'z48',
           'z49',
           'z50',
           'z51',
           'z52',
           'z53',
           'z54',
           'z55',
           'z56',
           'z57',
           'z58',
           'z59',
           'z60',
           'z61',
           'z62',
           'z63',
           'z64',
           'z65',
           'z66',
           'z67',
           'z68',
           'z69',
           'z70',
           'z71',
           'z72',
           'z73',
           'z74',
           'z75',
           'z76',
           'z77',
           'z78',
           'z79',
           'z80',
           'z81',
           'z82',
           'z83',
           'z84',
           'z85',
           'z86',
           'z87',
           'z88',
           'z89',
           'z90',
           'z91',
           'z92',
           'z93',
           'z94',
           'z95',
           'z96',
           'z97',
           'z98',
           'z99'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeMIMETypes': ['application/zip',
           'application/x-zip',
           'application/x-zip-compressed'],
          'CFBundleTypeName': 'Zip Archive',
          'CFBundleTypeOSTypes': ['ZIP ', 'ZIP_'],
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['com.pkware.zip-archive',
           'public.zip-archive',
           'public.zip-archive.first-part'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['rar',
           'r00',
           'r01',
           'r02',
           'r03',
           'r04',
           'r05',
           'r06',
           'r07',
           'r08',
           'r09',
           'r10',
           'r11',
           'r12',
           'r13',
           'r14',
           'r15',
           'r16',
           'r17',
           'r18',
           'r19',
           'r20',
           'r21',
           'r22',
           'r23',
           'r24',
           'r25',
           'r26',
           'r27',
           'r28',
           'r29',
           'r30',
           'r31',
           'r32',
           'r33',
           'r34',
           'r35',
           'r36',
           'r37',
           'r38',
           'r39',
           'r40',
           'r41',
           'r42',
           'r43',
           'r44',
           'r45',
           'r46',
           'r47',
           'r48',
           'r49',
           'r50',
           'r51',
           'r52',
           'r53',
           'r54',
           'r55',
           'r56',
           'r57',
           'r58',
           'r59',
           'r60',
           'r61',
           'r62',
           'r63',
           'r64',
           'r65',
           'r66',
           'r67',
           'r68',
           'r69',
           'r70',
           'r71',
           'r72',
           'r73',
           'r74',
           'r75',
           'r76',
           'r77',
           'r78',
           'r79',
           'r80',
           'r81',
           'r82',
           'r83',
           'r84',
           'r85',
           'r86',
           'r87',
           'r88',
           'r89',
           'r90',
           'r91',
           'r92',
           'r93',
           'r94',
           'r95',
           'r96',
           'r97',
           'r98',
           'r99'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeMIMETypes': ['application/x-rar',
           'application/x-rar-compressed'],
          'CFBundleTypeName': 'RAR Archive',
          'CFBundleTypeOSTypes': ['RARf'],
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['com.rarlab.rar-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['7z'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeMIMETypes': ['application/x-7z-compressed'],
          'CFBundleTypeName': '7-Zip Archive',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['org.7-zip.7-zip-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['lha', 'lzh'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeMIMETypes': ['application/x-lzh-compressed',
           'application/lha',
           'application/x-lha',
           'application/lzh',
           'application/x-lzh'],
          'CFBundleTypeName': 'LHA Archive',
          'CFBundleTypeOSTypes': ['LHA '],
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['cx.c3.lha-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['gz', 'gzip'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeMIMETypes': ['application/gzip', 'application/x-gzip'],
          'CFBundleTypeName': 'Gzip File',
          'CFBundleTypeOSTypes': ['Gzip'],
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['org.gnu.gnu-zip-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['tgz', 'tar-gz'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'Gzip Tar Archive',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['org.gnu.gnu-zip-tar-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['bz2', 'bzip2', 'bz'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeMIMETypes': ['application/bzip2',
           'application/bzip',
           'application/x-bzip2',
           'application/x-bzip'],
          'CFBundleTypeName': 'Bzip2 File',
          'CFBundleTypeOSTypes': ['Bzp2'],
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['public.bzip2-archive', 'org.bzip.bzip2-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['tbz2', 'tbz'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'Bzip2 Tar Archive',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['public.tar-bzip2-archive',
           'org.bzip.bzip2-tar-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['xz'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeMIMETypes': ['application/x-xz'],
          'CFBundleTypeName': 'XZ File',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['org.tukaani.xz-archive', 'public.xz-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['txz'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'XZ Tar Archive',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['org.tukaani.xz-tar-archive',
           'public.tar-xz-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['xar'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'XAR Archive',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['com.apple.xar-archive', 'public.xar-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['tar'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeMIMETypes': ['application/x-tar', 'application/tar'],
          'CFBundleTypeName': 'Tar Archive',
          'CFBundleTypeOSTypes': ['TARF'],
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['public.tar-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['iso'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeMIMETypes': ['application/x-iso-image'],
          'CFBundleTypeName': 'ISO Disk Image',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['public.iso-image'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['gtar'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeMIMETypes': ['application/x-gtar', 'application/gnutar'],
          'CFBundleTypeName': 'GNU Tar Archive',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['org.gnu.gnu-tar-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['z'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeMIMETypes': ['application/x-compress',
           'application/x-compressed'],
          'CFBundleTypeName': 'Unix Compress File',
          'CFBundleTypeOSTypes': ['ZIVU'],
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['public.z-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['taz', 'tar-z'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'Unix Compress Tar Archive',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['cx.c3.compress-tar-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['lzma'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'LZMA File',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['org.tukaani.lzma-archive', 'public.lzma-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['lz', 'lzip'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'LZIP Archive',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['public.lzip-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML',
          'NeedsTarball': True,
          'OnTab': True,
          'UseFullTextOnTab': True},
         {'CFBundleTypeExtensions': ['tlz'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'LZIP Tarball Archive',
          'CFBundleTypeRole': 'Viewer',
          'IconVariant': 'rose',
          'IsTarball': True,
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['public.lzip-tar-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['lzop', 'lzo'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'LZOP Archive',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['public.lzop-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML',
          'NeedsTarball': True,
          'OnTab': True,
          'UseFullTextOnTab': True},
         {'CFBundleTypeExtensions': ['tzo'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'LZOP Tarball Archive',
          'CFBundleTypeRole': 'Viewer',
          'IsTarball': True,
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['public.lzop-tar-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['cab'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeMIMETypes': ['application/vnd.ms-cab-compressed'],
          'CFBundleTypeName': 'CAB Archive',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['com.microsoft.cab-archive', 'public.archive.cab'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['cpio'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeMIMETypes': ['application/x-cpio'],
          'CFBundleTypeName': 'CPIO Archive',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['public.cpio-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['cpgz'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'Gzip CPIO Archive',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['com.apple.bom-compressed-cpio'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['pax'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'PAX Archive',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['cx.c3.pax-archive', 'public.pax-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['ipa'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'iOS App Package',
          'CFBundleTypeRole': 'Viewer',
          'ExcludeFromDefaults': True,
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['com.apple.iTunes.ipa'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['apk', 'xapk'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeMIMETypes': ['application/vnd.android.package-archive'],
          'CFBundleTypeName': 'Android Application Package',
          'CFBundleTypeRole': 'Viewer',
          'ExcludeFromDefaults': True,
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['public.archive.apk', 'com.android.package-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['jar'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeMIMETypes': ['application/java-archive'],
          'CFBundleTypeName': 'Java Archive',
          'CFBundleTypeRole': 'Viewer',
          'ExcludeFromDefaults': True,
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['com.sun.java-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['war'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeMIMETypes': ['application/java-archive'],
          'CFBundleTypeName': 'Java Web Archive',
          'CFBundleTypeRole': 'Viewer',
          'ExcludeFromDefaults': True,
          'LSHandlerRank': 'Default',
          'LSItemContentTypes': ['com.sun.web-application-archive'],
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['cbz'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'Comic Book Zip Archive',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['cbr'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'Comic Book Rar Archive',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default',
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'},
         {'CFBundleTypeExtensions': ['a'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'Ar Archive',
          'CFBundleTypeRole': 'Viewer',
          'LSHandlerRank': 'Default'},
         {'CFBundleTypeExtensions': ['000',
           '001',
           '002',
           '003',
           '004',
           '005',
           '006',
           '007',
           '008',
           '009',
           '010',
           '011',
           '012',
           '013',
           '014',
           '015',
           '016',
           '017',
           '018',
           '019',
           '020',
           '021',
           '022',
           '023',
           '024',
           '025',
           '026',
           '027',
           '028',
           '029',
           '030',
           '031',
           '032',
           '033',
           '034',
           '035',
           '036',
           '037',
           '038',
           '039',
           '040',
           '041',
           '042',
           '043',
           '044',
           '045',
           '046',
           '047',
           '048',
           '049',
           '050',
           '051',
           '052',
           '053',
           '054',
           '055',
           '056',
           '057',
           '058',
           '059',
           '060',
           '061',
           '062',
           '063',
           '064',
           '065',
           '066',
           '067',
           '068',
           '069',
           '070',
           '071',
           '072',
           '073',
           '074',
           '075',
           '076',
           '077',
           '078',
           '079',
           '080',
           '081',
           '082',
           '083',
           '084',
           '085',
           '086',
           '087',
           '088',
           '089',
           '090',
           '091',
           '092',
           '093',
           '094',
           '095',
           '096',
           '097',
           '098',
           '099'],
          'CFBundleTypeIconFile': 'zip.icns',
          'CFBundleTypeName': 'Generic Archive Volume',
          'CFBundleTypeRole': 'Viewer',
          'ExcludeFromDefaults': True,
          'IsMultiVolume': 'YES',
          'LSHandlerRank': 'Default',
          'LSTypeIsPackage': False,
          'NSPersistentStoreTypeKey': 'XML'}]}
)
